version: 0.0
os: linux
files:
  - source: /deployment-archive/index.html
    destination: /var/www/html/index.html
file_exists_behavior: OVERWRITE
BeforeInstall:
  - location: /before_script.sh
    timeout: 300
    runas: root
ApplicationStop:
  - location: /after_script.sh
    timeout: 300
    runas: root
