version: 0.0
os: linux
files:
  - source: /deployment-archive/index.html
    destination: /var/www/html/index.html
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: before_script.sh
      timeout: 300
ApplicationStop:
  - location: after_script.sh
    timeout: 300
    
