version: 0.0
os: linux
files:
  - source: index.html
    destination: /var/www/html/
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/clean_directory.sh # Correct path to the script
      timeout: 300
      runas: root
