version: 0.0
os: linux
files:
  - source: /deployment-archive/index.html
    destination: /var/www/html/index.html
hooks:
  AfterInstall:
    - location: after_script.sh
      timeout: 300
  BeforeInstall:
    - location: before_script.sh
      timeout: 300
