version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: /before_install.sh
      timeout: 300
  AfterInstall:
    - location: /after_install.sh
      timeout: 300
  ApplicationStart:
    - location: /application_start.sh
      timeout: 300
  ValidateService:
    - location: /validate_service.sh
      timeout: 300
