version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Building application...
      - cp index.html /var/www/html/
artifacts:
  files:
    - index.html
